name: chatbot
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  chewie: ^1.11.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #intl: 0.19.0
  intl: ^0.20.0
  #lutter_m.p: ^8.1.1
  flutter_markdown: ^0.7.6+2
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  flutter_local_notifications: ^19.3.0
  latlong2: ^0.9.1
  logging: ^1.3.0
  mobile_scanner: ^6.0.6
  pdfx: ^2.8.0
  socket_io_client: ^3.0.2
  url_launcher: ^6.3.1
  video_player: ^2.9.3
  http: ^1.4.0
  flutter_map: ^8.1.1
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.2
  google_maps_flutter: ^2.12.3
  permission_handler: ^11.3.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sisa.png" # Ruta de tu icono
  adaptive_icon_background: "#ffffff" # Color de fondo (para Android)
  adaptive_icon_foreground: "assets/images/sisa.png" # Imagen para Android

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo_ucuenca_top.png
    - assets/images/sisa.png
    - assets/images/chatbot.png
    - assets/icons/chatbot.svg
    - assets/images/avatar.png
    - assets/videos/sample.mp4
    - assets/videos/automuestreo.mp4
    - assets/videos/short.mp4
    - assets/images/clias.jpg
    - assets/images/idrc.png
    - assets/images/logo_clias.png
    - assets/offline_messages.json
    - assets/offline_form.json